language: python
python:
  - "2.7"
install:
  - pip install MySQL-python coverage
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - echo "#!/usr/bin/python" > config.py
script: nosetests -v --with-coverage --cover-branch --cover-erase --cover-package api.py

